# Generated by Django 4.2 on 2023-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_image_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guest_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_of_guests',
            field=models.IntegerField(default=1),
        ),
    ]
