# Generated by Django 4.2 on 2023-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(upload_to='media/facility_images'),
        ),
    ]
